/*
 * Vertex Platform API
 * The Vertex distributed cloud rendering platform includes a set of APIs and SDKs, which together allow easily integrating 3D product data into your business application.  See our [Developer Guides](https://developer.vertexvis.com/docs/guides/render-your-first-scene) to get started.  Notes about the Postman collection and API Reference code samples:   - They include all required and optional body parameters for completeness. Remove any optional parameters as desired.   - They use auto-generated IDs and other values that may share the same value for ease of documentation only. In actual requests and responses, the IDs should uniquely identify their corresponding resource. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@vertexvis.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vertexvis.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vertexvis.model.SelectFileById;
import com.vertexvis.model.SelectFileBySuppliedId;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents a file and directory within an archive.
 */
@ApiModel(description = "Represents a file and directory within an archive.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ArchiveManifestEntry {
  public static final String SERIALIZED_NAME_SELECTOR = "selector";
  @SerializedName(SERIALIZED_NAME_SELECTOR)
  private OneOfSelectFileByIdSelectFileBySuppliedId selector;

  public static final String SERIALIZED_NAME_DIRECTORY = "directory";
  @SerializedName(SERIALIZED_NAME_DIRECTORY)
  private String directory;

  public ArchiveManifestEntry() { 
  }

  public ArchiveManifestEntry selector(OneOfSelectFileByIdSelectFileBySuppliedId selector) {
    
    this.selector = selector;
    return this;
  }

   /**
   * Represents a query to select a file.
   * @return selector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "Represents a query to select a file.")

  public OneOfSelectFileByIdSelectFileBySuppliedId getSelector() {
    return selector;
  }


  public void setSelector(OneOfSelectFileByIdSelectFileBySuppliedId selector) {
    this.selector = selector;
  }


  public ArchiveManifestEntry directory(String directory) {
    
    this.directory = directory;
    return this;
  }

   /**
   * The directory in the archive where the file will be placed.
   * @return directory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The directory in the archive where the file will be placed.")

  public String getDirectory() {
    return directory;
  }


  public void setDirectory(String directory) {
    this.directory = directory;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArchiveManifestEntry archiveManifestEntry = (ArchiveManifestEntry) o;
    return Objects.equals(this.selector, archiveManifestEntry.selector) &&
        Objects.equals(this.directory, archiveManifestEntry.directory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(selector, directory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArchiveManifestEntry {\n");
    sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
    sb.append("    directory: ").append(toIndentedString(directory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

