/*
 * Vertex Platform API
 * The Vertex distributed cloud rendering platform includes a set of APIs and SDKs, which together allow easily integrating 3D product data into your business application.  See our [Developer Guides](https://developer.vertexvis.com/docs/guides/render-your-first-scene) to get started.  Notes about the Postman collection and API Reference code samples:   - They include all required and optional body parameters for completeness. Remove any optional parameters as desired.   - They use auto-generated IDs and other values that may share the same value for ease of documentation only. In actual requests and responses, the IDs should uniquely identify their corresponding resource. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@vertexvis.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vertexvis.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vertexvis.model.PermissionGrantee;
import com.vertexvis.model.PermissionSubject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreatePermissionGrantDataAttributes
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreatePermissionGrantDataAttributes {
  public static final String SERIALIZED_NAME_GRANTEE = "grantee";
  @SerializedName(SERIALIZED_NAME_GRANTEE)
  private PermissionGrantee grantee;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  private PermissionSubject subject;

  /**
   * Gets or Sets capability
   */
  @JsonAdapter(CapabilityEnum.Adapter.class)
  public enum CapabilityEnum {
    READ("read");

    private String value;

    CapabilityEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CapabilityEnum fromValue(String value) {
      for (CapabilityEnum b : CapabilityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CapabilityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CapabilityEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CapabilityEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CapabilityEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CAPABILITY = "capability";
  @SerializedName(SERIALIZED_NAME_CAPABILITY)
  private CapabilityEnum capability;

  public CreatePermissionGrantDataAttributes() { 
  }

  public CreatePermissionGrantDataAttributes grantee(PermissionGrantee grantee) {
    
    this.grantee = grantee;
    return this;
  }

   /**
   * Get grantee
   * @return grantee
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public PermissionGrantee getGrantee() {
    return grantee;
  }


  public void setGrantee(PermissionGrantee grantee) {
    this.grantee = grantee;
  }


  public CreatePermissionGrantDataAttributes subject(PermissionSubject subject) {
    
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public PermissionSubject getSubject() {
    return subject;
  }


  public void setSubject(PermissionSubject subject) {
    this.subject = subject;
  }


  public CreatePermissionGrantDataAttributes capability(CapabilityEnum capability) {
    
    this.capability = capability;
    return this;
  }

   /**
   * Get capability
   * @return capability
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public CapabilityEnum getCapability() {
    return capability;
  }


  public void setCapability(CapabilityEnum capability) {
    this.capability = capability;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePermissionGrantDataAttributes createPermissionGrantDataAttributes = (CreatePermissionGrantDataAttributes) o;
    return Objects.equals(this.grantee, createPermissionGrantDataAttributes.grantee) &&
        Objects.equals(this.subject, createPermissionGrantDataAttributes.subject) &&
        Objects.equals(this.capability, createPermissionGrantDataAttributes.capability);
  }

  @Override
  public int hashCode() {
    return Objects.hash(grantee, subject, capability);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePermissionGrantDataAttributes {\n");
    sb.append("    grantee: ").append(toIndentedString(grantee)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    capability: ").append(toIndentedString(capability)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

