/*
 * Vertex Platform API
 * The Vertex distributed cloud rendering platform includes a set of APIs and SDKs, which together allow easily integrating 3D product data into your business application.  See our [Developer Guides](https://developer.vertexvis.com/docs/guides/render-your-first-scene) to get started.  Notes about the Postman collection and API Reference code samples:   - They include all required and optional body parameters for completeness. Remove any optional parameters as desired.   - They use auto-generated IDs and other values that may share the same value for ease of documentation only. In actual requests and responses, the IDs should uniquely identify their corresponding resource. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@vertexvis.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vertexvis.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vertexvis.model.OrthographicCamera;
import com.vertexvis.model.PerspectiveCamera;
import com.vertexvis.model.Vector3;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.vertexvis.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class CreateSceneViewRequestDataAttributesCamera extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(CreateSceneViewRequestDataAttributesCamera.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!CreateSceneViewRequestDataAttributesCamera.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'CreateSceneViewRequestDataAttributesCamera' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<PerspectiveCamera> adapterPerspectiveCamera = gson.getDelegateAdapter(this, TypeToken.get(PerspectiveCamera.class));
            final TypeAdapter<OrthographicCamera> adapterOrthographicCamera = gson.getDelegateAdapter(this, TypeToken.get(OrthographicCamera.class));

            return (TypeAdapter<T>) new TypeAdapter<CreateSceneViewRequestDataAttributesCamera>() {
                @Override
                public void write(JsonWriter out, CreateSceneViewRequestDataAttributesCamera value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `PerspectiveCamera`
                    if (value.getActualInstance() instanceof PerspectiveCamera) {
                        JsonElement element = adapterPerspectiveCamera.toJsonTree((PerspectiveCamera)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `OrthographicCamera`
                    if (value.getActualInstance() instanceof OrthographicCamera) {
                        JsonElement element = adapterOrthographicCamera.toJsonTree((OrthographicCamera)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: OrthographicCamera, PerspectiveCamera");
                }

                @Override
                public CreateSceneViewRequestDataAttributesCamera read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize PerspectiveCamera
                    try {
                        // validate the JSON object to see if any exception is thrown
                        PerspectiveCamera.validateJsonElement(jsonElement);
                        actualAdapter = adapterPerspectiveCamera;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'PerspectiveCamera'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for PerspectiveCamera failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'PerspectiveCamera'", e);
                    }
                    // deserialize OrthographicCamera
                    try {
                        // validate the JSON object to see if any exception is thrown
                        OrthographicCamera.validateJsonElement(jsonElement);
                        actualAdapter = adapterOrthographicCamera;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'OrthographicCamera'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for OrthographicCamera failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'OrthographicCamera'", e);
                    }

                    if (match == 1) {
                        CreateSceneViewRequestDataAttributesCamera ret = new CreateSceneViewRequestDataAttributesCamera();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for CreateSceneViewRequestDataAttributesCamera: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public CreateSceneViewRequestDataAttributesCamera() {
        super("oneOf", Boolean.FALSE);
    }

    public CreateSceneViewRequestDataAttributesCamera(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("PerspectiveCamera", PerspectiveCamera.class);
        schemas.put("OrthographicCamera", OrthographicCamera.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return CreateSceneViewRequestDataAttributesCamera.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * OrthographicCamera, PerspectiveCamera
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof PerspectiveCamera) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof OrthographicCamera) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be OrthographicCamera, PerspectiveCamera");
    }

    /**
     * Get the actual instance, which can be the following:
     * OrthographicCamera, PerspectiveCamera
     *
     * @return The actual instance (OrthographicCamera, PerspectiveCamera)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `PerspectiveCamera`. If the actual instance is not `PerspectiveCamera`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PerspectiveCamera`
     * @throws ClassCastException if the instance is not `PerspectiveCamera`
     */
    public PerspectiveCamera getPerspectiveCamera() throws ClassCastException {
        return (PerspectiveCamera)super.getActualInstance();
    }

    /**
     * Get the actual instance of `OrthographicCamera`. If the actual instance is not `OrthographicCamera`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `OrthographicCamera`
     * @throws ClassCastException if the instance is not `OrthographicCamera`
     */
    public OrthographicCamera getOrthographicCamera() throws ClassCastException {
        return (OrthographicCamera)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to CreateSceneViewRequestDataAttributesCamera
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with PerspectiveCamera
        try {
            PerspectiveCamera.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for PerspectiveCamera failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with OrthographicCamera
        try {
            OrthographicCamera.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for OrthographicCamera failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for CreateSceneViewRequestDataAttributesCamera with oneOf schemas: OrthographicCamera, PerspectiveCamera. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of CreateSceneViewRequestDataAttributesCamera given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of CreateSceneViewRequestDataAttributesCamera
     * @throws IOException if the JSON string is invalid with respect to CreateSceneViewRequestDataAttributesCamera
     */
    public static CreateSceneViewRequestDataAttributesCamera fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, CreateSceneViewRequestDataAttributesCamera.class);
    }

    /**
     * Convert an instance of CreateSceneViewRequestDataAttributesCamera to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

