/*
 * Vertex Platform API
 * The Vertex distributed cloud rendering platform includes a set of APIs and SDKs, which together allow easily integrating 3D product data into your business application.  See our [Developer Guides](https://developer.vertexvis.com/docs/guides/render-your-first-scene) to get started.  Notes about the Postman collection and API Reference code samples,   - They include all required and optional body parameters for completeness. Remove any optional parameters as desired.   - They use auto-generated IDs and other values that may share the same value for ease of documentation only. In actual requests and responses, the IDs should uniquely identify their corresponding resource. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@vertexvis.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vertexvis.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vertexvis.model.CameraFit;
import com.vertexvis.model.OrthographicCamera;
import com.vertexvis.model.PerspectiveCamera;
import com.vertexvis.model.Vector3;
import java.io.IOException;
import java.math.BigDecimal;

import javax.ws.rs.core.GenericType;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;

import com.vertexvis.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UpdateSceneViewRequestDataAttributesCamera extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(UpdateSceneViewRequestDataAttributesCamera.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!UpdateSceneViewRequestDataAttributesCamera.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'UpdateSceneViewRequestDataAttributesCamera' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<CameraFit> adapterCameraFit = gson.getDelegateAdapter(this, TypeToken.get(CameraFit.class));
            final TypeAdapter<OrthographicCamera> adapterOrthographicCamera = gson.getDelegateAdapter(this, TypeToken.get(OrthographicCamera.class));
            final TypeAdapter<PerspectiveCamera> adapterPerspectiveCamera = gson.getDelegateAdapter(this, TypeToken.get(PerspectiveCamera.class));

            return (TypeAdapter<T>) new TypeAdapter<UpdateSceneViewRequestDataAttributesCamera>() {
                @Override
                public void write(JsonWriter out, UpdateSceneViewRequestDataAttributesCamera value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `CameraFit`
                    if (value.getActualInstance() instanceof CameraFit) {
                        JsonObject obj = adapterCameraFit.toJsonTree((CameraFit)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `OrthographicCamera`
                    if (value.getActualInstance() instanceof OrthographicCamera) {
                        JsonObject obj = adapterOrthographicCamera.toJsonTree((OrthographicCamera)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `PerspectiveCamera`
                    if (value.getActualInstance() instanceof PerspectiveCamera) {
                        JsonObject obj = adapterPerspectiveCamera.toJsonTree((PerspectiveCamera)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemas: CameraFit, OrthographicCamera, PerspectiveCamera");
                }

                @Override
                public UpdateSceneViewRequestDataAttributesCamera read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonObject jsonObject = elementAdapter.read(in).getAsJsonObject();

                    // deserialize CameraFit
                    try {
                        // validate the JSON object to see if any exception is thrown
                        CameraFit.validateJsonObject(jsonObject);
                        log.log(Level.FINER, "Input data matches schema 'CameraFit'");
                        UpdateSceneViewRequestDataAttributesCamera ret = new UpdateSceneViewRequestDataAttributesCamera();
                        ret.setActualInstance(adapterCameraFit.fromJsonTree(jsonObject));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        log.log(Level.FINER, "Input data does not match schema 'CameraFit'", e);
                    }

                    // deserialize OrthographicCamera
                    try {
                        // validate the JSON object to see if any exception is thrown
                        OrthographicCamera.validateJsonObject(jsonObject);
                        log.log(Level.FINER, "Input data matches schema 'OrthographicCamera'");
                        UpdateSceneViewRequestDataAttributesCamera ret = new UpdateSceneViewRequestDataAttributesCamera();
                        ret.setActualInstance(adapterOrthographicCamera.fromJsonTree(jsonObject));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        log.log(Level.FINER, "Input data does not match schema 'OrthographicCamera'", e);
                    }

                    // deserialize PerspectiveCamera
                    try {
                        // validate the JSON object to see if any exception is thrown
                        PerspectiveCamera.validateJsonObject(jsonObject);
                        log.log(Level.FINER, "Input data matches schema 'PerspectiveCamera'");
                        UpdateSceneViewRequestDataAttributesCamera ret = new UpdateSceneViewRequestDataAttributesCamera();
                        ret.setActualInstance(adapterPerspectiveCamera.fromJsonTree(jsonObject));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        log.log(Level.FINER, "Input data does not match schema 'PerspectiveCamera'", e);
                    }


                    throw new IOException(String.format("Failed deserialization for UpdateSceneViewRequestDataAttributesCamera: no class matched. JSON: %s", jsonObject.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, GenericType> schemas = new HashMap<String, GenericType>();

    public UpdateSceneViewRequestDataAttributesCamera() {
        super("anyOf", Boolean.FALSE);
    }

    public UpdateSceneViewRequestDataAttributesCamera(CameraFit o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public UpdateSceneViewRequestDataAttributesCamera(OrthographicCamera o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public UpdateSceneViewRequestDataAttributesCamera(PerspectiveCamera o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("CameraFit", new GenericType<CameraFit>() {
        });
        schemas.put("OrthographicCamera", new GenericType<OrthographicCamera>() {
        });
        schemas.put("PerspectiveCamera", new GenericType<PerspectiveCamera>() {
        });
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return UpdateSceneViewRequestDataAttributesCamera.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * CameraFit, OrthographicCamera, PerspectiveCamera
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof CameraFit) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof OrthographicCamera) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof PerspectiveCamera) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be CameraFit, OrthographicCamera, PerspectiveCamera");
    }

    /**
     * Get the actual instance, which can be the following:
     * CameraFit, OrthographicCamera, PerspectiveCamera
     *
     * @return The actual instance (CameraFit, OrthographicCamera, PerspectiveCamera)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `CameraFit`. If the actual instance is not `CameraFit`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CameraFit`
     * @throws ClassCastException if the instance is not `CameraFit`
     */
    public CameraFit getCameraFit() throws ClassCastException {
        return (CameraFit)super.getActualInstance();
    }

    /**
     * Get the actual instance of `OrthographicCamera`. If the actual instance is not `OrthographicCamera`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `OrthographicCamera`
     * @throws ClassCastException if the instance is not `OrthographicCamera`
     */
    public OrthographicCamera getOrthographicCamera() throws ClassCastException {
        return (OrthographicCamera)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PerspectiveCamera`. If the actual instance is not `PerspectiveCamera`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PerspectiveCamera`
     * @throws ClassCastException if the instance is not `PerspectiveCamera`
     */
    public PerspectiveCamera getPerspectiveCamera() throws ClassCastException {
        return (PerspectiveCamera)super.getActualInstance();
    }


 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UpdateSceneViewRequestDataAttributesCamera
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
    // validate anyOf schemas one by one
    int validCount = 0;
    // validate the json string with CameraFit
    try {
      CameraFit.validateJsonObject(jsonObj);
      return; // return earlier as at least one schema is valid with respect to the Json object
      //validCount++;
    } catch (Exception e) {
      // continue to the next one
    }
    // validate the json string with OrthographicCamera
    try {
      OrthographicCamera.validateJsonObject(jsonObj);
      return; // return earlier as at least one schema is valid with respect to the Json object
      //validCount++;
    } catch (Exception e) {
      // continue to the next one
    }
    // validate the json string with PerspectiveCamera
    try {
      PerspectiveCamera.validateJsonObject(jsonObj);
      return; // return earlier as at least one schema is valid with respect to the Json object
      //validCount++;
    } catch (Exception e) {
      // continue to the next one
    }
    if (validCount == 0) {
      throw new IOException(String.format("The JSON string is invalid for UpdateSceneViewRequestDataAttributesCamera with anyOf schemas: CameraFit, OrthographicCamera, PerspectiveCamera. JSON: %s", jsonObj.toString()));
    }
  }

 /**
  * Create an instance of UpdateSceneViewRequestDataAttributesCamera given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UpdateSceneViewRequestDataAttributesCamera
  * @throws IOException if the JSON string is invalid with respect to UpdateSceneViewRequestDataAttributesCamera
  */
  public static UpdateSceneViewRequestDataAttributesCamera fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateSceneViewRequestDataAttributesCamera.class);
  }

 /**
  * Convert an instance of UpdateSceneViewRequestDataAttributesCamera to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

