/*
 * Vertex Platform API
 * The Vertex distributed cloud rendering platform includes a set of APIs and SDKs, which together allow easily integrating 3D product data into your business application.  See our [Developer Guides](https://developer.vertexvis.com/docs/guides/render-your-first-scene) to get started.  Notes about the Postman collection and API Reference code samples,   - They include all required and optional body parameters for completeness. Remove any optional parameters as desired.   - They use auto-generated IDs and other values that may share the same value for ease of documentation only. In actual requests and responses, the IDs should uniquely identify their corresponding resource. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@vertexvis.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vertexvis.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vertexvis.model.WebhookEventDataRelationshipsOwnerData;
import com.vertexvis.model.WebhookEventDataRelationshipsOwnerLinks;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Relationship to an &#x60;owner&#x60;.
 */
@ApiModel(description = "Relationship to an `owner`.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WebhookEventDataRelationshipsOwner {
  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private WebhookEventDataRelationshipsOwnerData data;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private Map<String, WebhookEventDataRelationshipsOwnerLinks> links = null;


  public WebhookEventDataRelationshipsOwner data(WebhookEventDataRelationshipsOwnerData data) {
    
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(required = true, value = "")

  public WebhookEventDataRelationshipsOwnerData getData() {
    return data;
  }


  public void setData(WebhookEventDataRelationshipsOwnerData data) {
    this.data = data;
  }


  public WebhookEventDataRelationshipsOwner links(Map<String, WebhookEventDataRelationshipsOwnerLinks> links) {
    
    this.links = links;
    return this;
  }

  public WebhookEventDataRelationshipsOwner putLinksItem(String key, WebhookEventDataRelationshipsOwnerLinks linksItem) {
    if (this.links == null) {
      this.links = new HashMap<>();
    }
    this.links.put(key, linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, WebhookEventDataRelationshipsOwnerLinks> getLinks() {
    return links;
  }


  public void setLinks(Map<String, WebhookEventDataRelationshipsOwnerLinks> links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookEventDataRelationshipsOwner webhookEventDataRelationshipsOwner = (WebhookEventDataRelationshipsOwner) o;
    return Objects.equals(this.data, webhookEventDataRelationshipsOwner.data) &&
        Objects.equals(this.links, webhookEventDataRelationshipsOwner.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookEventDataRelationshipsOwner {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

