apiPackage: com.vertexvis.api
artifactDescription: The Vertex platform API client for Java.
artifactId: vertex-api-client
artifactUrl: https://github.com/Vertexvis/vertex-api-client-java
artifactVersion: 0.1.0
dateLibrary: java8
developerEmail: support@vertexvis.com
developerName: Vertex Developers
developerOrganization: Vertex Software
developerOrganizationUrl: https://vertexvis.com
java8: true
groupId: com.vertexvis
hideGenerationTimestamp: true
invokerPackage: com.vertexvis
licenseName: MIT
licenseUrl: https://opensource.org/licenses/MIT
modelPackage: com.vertexvis.model
scmConnection: scm:git:git@github.com:vertexvis/vertex-api-client-java.git
scmDeveloperConnection: scm:git:git@github.com:vertexvis/vertex-api-client-java.git
scmUrl: https://github.com/Vertexvis/vertex-api-client-java
