/*
 * Vertex Platform API
 * The Vertex distributed cloud rendering platform includes a set of APIs and SDKs, which together allow easily integrating 3D product data into your business application.  See our [Developer Guides](https://developer.vertexvis.com/docs/guides/render-your-first-scene) to get started.  Notes about the Postman collection and API Reference code samples,   - They include all required and optional body parameters for completeness. Remove any optional parameters as desired.   - They use auto-generated IDs and other values that may share the same value for ease of documentation only. In actual requests and responses, the IDs should uniquely identify their corresponding resource. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@vertexvis.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vertexvis.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vertexvis.model.SceneItemRelationship;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateSceneItemOverrideRequestDataRelationships
 */
public class CreateSceneItemOverrideRequestDataRelationshipsTest {
    private final CreateSceneItemOverrideRequestDataRelationships model = new CreateSceneItemOverrideRequestDataRelationships();

    /**
     * Model tests for CreateSceneItemOverrideRequestDataRelationships
     */
    @Test
    public void testCreateSceneItemOverrideRequestDataRelationships() {
        // TODO: test CreateSceneItemOverrideRequestDataRelationships
    }

    /**
     * Test the property 'sceneItem'
     */
    @Test
    public void sceneItemTest() {
        // TODO: test sceneItem
    }

}
