name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { java-version: 17, distribution: temurin }
      - name: Build and Verify
        run: |
          # Build and publish the plugin to Maven Local first
          ./gradlew :openapi-generator-plugin:build :openapi-generator-plugin:publishToMavenLocal

          # Now run the full build (this will use the plugin from Maven Local)
          ./gradlew clean build
