name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { java-version: 17, distribution: temurin }
      - name: Build and Verify
        run: |
          # Build the plugin first and check its contents
          ./gradlew :openapi-generator-plugin:build

          # Now run the full build
          ./gradlew clean build
