name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with: { java-version: 11, distribution: adopt }
      - name: Build and Verify
        run: ./gradlew build
