name: PR Snapshot

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      
      - name: Build and Publish Snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          # Build the plugin first
          ./gradlew :openapi-generator-plugin:build
          
          # Publish snapshots to GitHub Packages
          ./gradlew -PisSnapshot=true :openapi-generator-plugin:publish :api-client-library:publish
