name: publish

on: { push: { branches: [main] } }

jobs:
  detect-publish:
    runs-on: ubuntu-latest
    outputs:
      publish: ${{ steps.detect-publish.outputs.publish }}
    steps:
      - uses: actions/checkout@v4
      - id: detect-publish
        run: |
          result=$(./scripts/detect-publish.sh)
          echo $result
          echo ::set-output name=publish::$result

  publish:
    runs-on: ubuntu-latest
    needs: [detect-publish]
    if: needs.detect-publish.outputs.publish == 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { java-version: 17, distribution: temurin }
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          ./gradlew \
            -P signingKey=${{ secrets.ORG_GRADLE_PROJECT_signingKey }} \
            -P signingPassword=${{ secrets.ORG_GRADLE_PROJECT_signingPassword }} \
            -P ossrhUsername=${{ secrets.OSSRH_USERNAME }} \
            -P ossrhPassword=${{ secrets.OSSRH_PASSWORD }} \
            publishToSonatype \
            closeAndReleaseSonatypeStagingRepository
          ./scripts/publish.sh
